SRC = main.cpp

HHHHH = Read_and_replace_for

TRASH_DIR = .trash

OBJ = $(addprefix $(TRASH_DIR)/, $(SRC:.cpp=.o))

FLAGS = -std=c++98 -Wall -Werror -Wextra

CC = c++

$(TRASH_DIR):
	mkdir -p $(TRASH_DIR)

$(TRASH_DIR)/%.o: %.cpp | $(TRASH_DIR)
	$(CC) $(FLAGS) -c $< -o $@

all: $(HHHHH)

$(HHHHH): $(OBJ)
	$(CC) $(FLAGS) $(OBJ) -o $(HHHHH)

clean:
	rm -rf $(TRASH_DIR)

fclean: clean
	rm -rf $(HHHHH)

re: fclean all

.PHONY: all clean fclean re

